[private]
default: help

dev:
  bun run dev

build:
  bun run build

publish:
	./build.sh


# Shows this message
help:
  @just --list

# runs a checkup
doctor:
    #!/usr/bin/env bash
    command -v bun >/dev/null && printf "bun = \033[1;32myes\033[0m ($(bun --version))\n" || printf "bun = \033[1;31mno\033[0m\n"
    command -v node >/dev/null && printf "node = \033[1;32myes\033[0m ($(node --version))\n" || printf "node = \033[1;31mno\033[0m\n"
