export BUILDX_BAKE_ENTITLEMENTS_FS := "0"

stable-all:
    TAG=stable docker buildx bake --push

dev-all:
    TAG=dev docker buildx bake --push

build service:
    docker buildx bake {{service}} --push

build-stable service:
    TAG=stable docker buildx bake {{service}} --push

clean:
    docker builder prune --filter type=exec.cachemount
