export BUILDX_BAKE_ENTITLEMENTS_FS := "0"

default: help

stable-all:
    TAG=stable docker buildx bake --push

dev-all:
    TAG=dev docker buildx bake --push

build service:
    docker buildx bake {{service}} --push

build-stable service:
    TAG=stable docker buildx bake {{service}} --push

run-migrations:
	#!/usr/bin/env bash
	dirs=("auth_backend" "gradegetter/gradegetter" "gradegetter/gradegetter_backend" "notification_backend" "smalltalk_backend")
	for d in "${dirs[@]}"; do
		(
			cd "$d"
			cargo sqlx db create
			cargo sqlx mig run
		)
	done

clean:
    docker builder prune --filter type=exec.cachemount

help:
    @just --list
