export BUILDX_BAKE_ENTITLEMENTS_FS := "0"

[private]
default: help

stable-all:
    TAG=stable docker buildx bake --push

dev-all:
    TAG=dev docker buildx bake --push

build service:
    docker buildx bake {{service}} --push

build-stable service:
    TAG=stable docker buildx bake {{service}} --push

run-migrations:
	#!/usr/bin/env bash
	dirs=("auth_backend" "gradegetter/gradegetter_backend" "notification_backend" "smalltalk_backend")
	for d in "${dirs[@]}"; do
		(
			echo "Migrations for $d running"
			cd "$d"
			cargo sqlx db create
			cargo sqlx mig run
		)
	done

prepare:
	#!/usr/bin/env bash
	dirs=("auth_backend" "gradegetter/gradegetter" "gradegetter/gradegetter_backend" "notification_backend" "smalltalk_backend")
	for d in "${dirs[@]}"; do
		(
			echo "$d"
			cd "$d"
			cargo sqlx prepare
		)
	done

clean:
    docker builder prune --filter type=exec.cachemount

doctor:
  #!/usr/bin/env bash
    command -v docker >/dev/null 2>&1 && printf "docker = \033[1;32myes\033[0m\n" || printf "docker = \033[1;31mno\033[0m\n"
    command -v cargo-sqlx >/dev/null && printf "cargo-sqlx = \033[1;32myes\033[0m\n" || printf "cargo-sqlx = \033[1;31mno\033[0m\n" 
    cargo --version

help:
    @just --list
