#!/bin/sh

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
SYSROOT="$ROOT_DIR/target/.sysroots/x86_64"

exec clang \
  --target=x86_64-unknown-linux-gnu \
  --sysroot="$SYSROOT" \
  --gcc-toolchain="$SYSROOT/usr" \
  -fuse-ld=lld \
  "$@"
