server {
    listen 0.0.0.0:80;
    listen [::]:80;
    server_name _;
    root /usr/share/nginx/html;

    absolute_redirect off;

    location = / {
        return 301 /book/;
    }

    location /book {
        return 301 /book/;
    }
    location /book/ {
        alias /usr/share/nginx/html/book/;
        index index.html;
        try_files $uri $uri/ /book/index.html;
    }

    location /rustdoc {
        return 301 /rustdocs/;
    }

    location /rustdocs {
        return 301 /rustdocs/;
    }

    location /rustdocs/ {
        alias /usr/share/nginx/html/rustdocs/;
        autoindex on;
    }

}
