/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/global_message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["global_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/revoke_all/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke_all_from_id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_by_id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/evict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["evict_from_hashset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["change_role"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/users/{uuid}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_user_roles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["logout_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_handler"];
        options?: never;
        head?: never;
        patch: operations["add_account_info"];
        trace?: never;
    };
    "/me/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["add_recovery_info"];
        trace?: never;
    };
    "/me/recovery/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify_recovery_info"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/session/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke_specific_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_active_sessions"];
        put?: never;
        post?: never;
        delete: operations["revoke_all_sessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/by-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["get_users_by_ids"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActiveSessions: {
            /** Format: date-time */
            expires_at: string;
            is_current: boolean;
            /** Format: uuid */
            session_id: string;
            user_agent: string;
        };
        AddRecoveryInfoInputs: {
            encrypted_private_key: string;
            recovery_hash: string;
        };
        AuthenticatedUser: {
            role: components["schemas"]["UserRole"];
            username: string;
            /** Format: uuid */
            uuid: string;
        };
        ByIdsInput: {
            ids: string[];
        };
        ChangeRoleInput: {
            role: components["schemas"]["UserRole"];
            service: components["schemas"]["ServiceName"];
        };
        Claims: {
            /** Format: date-time */
            exp: string;
            /** Format: date-time */
            iat: string;
            public_key?: string | null;
            roles: components["schemas"]["HashMap"];
            /** Format: uuid */
            sub: string;
            username: string;
        };
        HashMap: {
            [key: string]: "devin" | "owen" | "mrd" | "trusted" | "user";
        };
        LoginInput: {
            /** @example password */
            password: string;
            /** @example user */
            username: string;
        };
        LoginOutput: {
            access_token: string;
        };
        MessageFromFrontend: {
            content: string;
            title: string;
        };
        RegisterInput: {
            /** @example password */
            password: string;
            /** @example user */
            username: string;
        };
        /** @enum {string} */
        ServiceName: "global" | "gradegetter" | "smalltalk" | "notifications" | "podcastschoolproject";
        UpdateProfileInput: {
            bio?: string | null;
            last_seen_visible?: boolean | null;
            public_key?: string | null;
        };
        /** @enum {string} */
        UserRole: "devin" | "owen" | "mrd" | "trusted" | "user";
        UserSearchResult: {
            bio?: string | null;
            /** Format: uuid */
            id: string;
            public_key?: string | null;
            username: string;
        };
        Users: {
            /** Format: uuid */
            id: string;
            roles: components["schemas"]["HashMap"];
            username: string;
        };
        VerifyRecoveryInfoInputs: {
            recovery_hash: string;
        };
        VerifyRecoveryInfoOutputs: {
            encrypted_private_key: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    global_message: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageFromFrontend"];
            };
        };
        responses: {
            /** @description goodbye user, hello admin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description token error i think */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description you arent supposed to be here IDIIOIOOOOT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_all_from_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the id of the user to revoke all refresh_tokens from */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description goodbye user, hello admin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description token error i think */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description you arent supposed to be here IDIIOIOOOOT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description hello admin!!!! hello little stylus, its devinlittle or owen kesterson inside the ADMINNNNNNN */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Users"][];
                };
            };
            /** @description token error i think */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description you arent supposed to be here STUPID */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the id of the user to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description goodbye user, hello admin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description token error i think */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description you arent supposed to be here IDIIOIOOOOT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    evict_from_hashset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the id of the user to evict from service hashsets */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description goodbye user, hello admin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description token error i think */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description you arent supposed to be here IDIIOIOOOOT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_role: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the id of the user to change the role */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleInput"];
            };
        };
        responses: {
            /** @description hello admin!!!! role changed 👀👀👀👀 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description token error i think */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description you arent supposed to be here IDIIOIOOOOT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user_roles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description pretty easy to understand what this means. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description sends back in json the users roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HashMap"];
                };
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Returns Valid JWT for User and SET_COOKIE header for refreshing purposes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOutput"];
                };
            };
            /** @description Credentials Incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sends back an empty, expired cookie to client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the refresh_token cookie the user send is messed tf up */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credentials Incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_account_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileInput"];
            };
        };
        responses: {
            /** @description added public key to db */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description jwt error */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_recovery_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRecoveryInfoInputs"];
            };
        };
        responses: {
            /** @description recovery info added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credentials Incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description information already there */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_recovery_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRecoveryInfoInputs"];
            };
        };
        responses: {
            /** @description recovery info added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyRecoveryInfoOutputs"];
                };
            };
            /** @description Credentials Incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the hashes do not match */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the hashes do not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_specific_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the id of the specific refesh_token */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description revoked specific token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credentials Incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_active_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description shows all the active sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveSessions"][];
                };
            };
            /** @description Credentials Incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_all_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description revoked all sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credentials Incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description sent back jwt and refresh_cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOutput"];
                };
            };
            /** @description cookie messed tf up */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInput"];
            };
        };
        responses: {
            /** @description Registers User! */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description User exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_users_by_ids: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ByIdsInput"];
            };
        };
        responses: {
            /** @description shows userinfo with provided ids */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSearchResult"][];
                };
            };
            /** @description Credentials Incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the hashes do not match */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the hashes do not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_user: {
        parameters: {
            query: {
                /** @description the user search query */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description show user search result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSearchResult"][];
                };
            };
            /** @description Credentials Incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the hashes do not match */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the hashes do not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
