/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/session_cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["internal_remove_all_session_listings"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_listings"];
        put?: never;
        post: operations["create_listing"];
        delete: operations["remove_listing"];
        options?: never;
        head?: never;
        patch: operations["modify_listing"];
        trace?: never;
    };
    "/listings/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["remove_all_session_listings"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FileListing: {
            auto_accept: boolean;
            /** Format: date-time */
            created_at: string;
            filename: string;
            /** Format: uuid */
            id: string;
            mime_type: string;
            /** Format: uuid */
            owner_id: string;
            owner_username: string;
            /** Format: uuid */
            session_id: string;
            /** Format: int64 */
            size_bytes: number;
            visibility: components["schemas"]["Visibility"];
        };
        FileListingInput: {
            auto_accept: boolean;
            /** Format: date-time */
            created_at: string;
            filename: string;
            mime_type: string;
            /** Format: uuid */
            owner_id: string;
            /** Format: uuid */
            session_id: string;
            /** Format: int64 */
            size_bytes: number;
            visibility: components["schemas"]["Visibility"];
        };
        /** @enum {string} */
        Namespaces: "notification" | "nanopass" | "gradegetter" | "smalltalk_keysync" | "smalltalk_notes";
        NanoPassMessage: {
            /** Format: uuid */
            from_session_id?: string | null;
            /** Format: uuid */
            from_user_id?: string | null;
            /** Format: uuid */
            id: string;
            namespace: components["schemas"]["Namespaces"];
            payload: components["schemas"]["NanoPassPayload"];
            /** Format: uuid */
            target_session_id?: string | null;
            /** Format: uuid */
            target_user_id?: string | null;
        };
        NanoPassPayload: {
            data: {
                /** Format: uuid */
                listing_id: string;
                /** Format: uuid */
                requester_session_id: string;
            };
            /** @enum {string} */
            type: "FileQuery";
        } | {
            data: {
                /** Format: uuid */
                host_session_id: string;
                /** Format: uuid */
                listing_id: string;
            };
            /** @enum {string} */
            type: "FileQueryResponse";
        } | {
            data: {
                /** Format: uuid */
                listing_id: string;
                /** Format: uuid */
                requester_session_id: string;
                requester_username: string;
            };
            /** @enum {string} */
            type: "TransferRequest";
        } | {
            data: {
                /** Format: uuid */
                listing_id: string;
            };
            /** @enum {string} */
            type: "TransferAccepted";
        } | {
            data: {
                /** Format: uuid */
                listing_id: string;
            };
            /** @enum {string} */
            type: "TransferDeclined";
        } | {
            data: {
                /** Format: uuid */
                listing_id: string;
                sdp: string;
            };
            /** @enum {string} */
            type: "SDPOffer";
        } | {
            data: {
                /** Format: uuid */
                listing_id: string;
                sdp: string;
            };
            /** @enum {string} */
            type: "SDPAnswer";
        } | {
            data: {
                candidate: string;
                /** Format: uuid */
                listing_id: string;
                sdp_mid?: string | null;
                /** Format: int32 */
                sdp_mline_index?: number | null;
            };
            /** @enum {string} */
            type: "ICECandidate";
        } | {
            data: {
                listing: components["schemas"]["FileListing"];
            };
            /** @enum {string} */
            type: "ListingAdded";
        } | {
            data: {
                listing: components["schemas"]["FileListing"];
            };
            /** @enum {string} */
            type: "ListingModified";
        } | {
            data: {
                listing: components["schemas"]["FileListing"];
            };
            /** @enum {string} */
            type: "ListingRemoved";
        };
        RemoveListingInput: {
            /** Format: uuid */
            listing_id: string;
        };
        RemoveSessionInput: {
            /** Format: uuid */
            session_id: string;
        };
        RemoveSessionInternalInput: {
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            user_id: string;
        };
        Visibility: {
            /** @enum {string} */
            type: "Private";
        } | {
            /** @enum {string} */
            type: "Public";
        } | {
            allowlist: string[];
            /** @enum {string} */
            type: "Restricted";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description returns 200 if service alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    internal_remove_all_session_listings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveSessionInternalInput"];
            };
        };
        responses: {
            /** @description all listing removed from a specific session_id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description uhmmm...failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_listings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description listing returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListing"][];
                };
            };
            /** @description uhmmm...failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_listing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileListingInput"];
            };
        };
        responses: {
            /** @description listing created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListing"];
                };
            };
            /** @description uhmmm...failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_listing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveListingInput"];
            };
        };
        responses: {
            /** @description listing removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description uhmmm...failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    modify_listing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileListing"];
            };
        };
        responses: {
            /** @description listing modified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description uhmmm...failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_all_session_listings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveSessionInput"];
            };
        };
        responses: {
            /** @description all listing removed from a specific session_id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description uhmmm...failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
