/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/delete/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_handler"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/invalidate/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["invalidate_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/group/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_group"];
        options?: never;
        head?: never;
        patch: operations["update_group"];
        trace?: never;
    };
    "/notes/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_note"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/note/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["soft_del_note"];
        options?: never;
        head?: never;
        patch: operations["update_note"];
        trace?: never;
    };
    "/notes/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["note_sync"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthenticatedUser: {
            role: components["schemas"]["UserRole"];
            /** Format: uuid */
            session_id: string;
            username: string;
            /** Format: uuid */
            uuid: string;
        };
        Claims: {
            /** Format: date-time */
            exp: string;
            /** Format: date-time */
            iat: string;
            public_key?: string | null;
            roles: components["schemas"]["HashMap"];
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            sub: string;
            username: string;
        };
        HashMap: {
            [key: string]: "devin" | "owen" | "mrd" | "trusted" | "user";
        };
        /** @enum {string} */
        Namespaces: "notification" | "nanopass" | "gradegetter" | "smalltalk_keysync" | "smalltalk_notes";
        NoteCreateRequest: {
            /** Format: binary */
            enc_name?: string | null;
            is_protected: boolean;
            password_hash?: string | null;
            /** Format: binary */
            salt?: string | null;
        };
        NoteGroupCreateRequest: {
            /** Format: binary */
            enc_group_metadata?: string | null;
            /** Format: binary */
            enc_group_name?: string | null;
        };
        NotePatchRequest: {
            /** Format: binary */
            enc_content?: string | null;
            /** Format: binary */
            enc_name?: string | null;
            is_deleted?: boolean | null;
            is_pinned?: boolean | null;
            is_protected?: boolean | null;
            password_hash?: string | null;
            /** Format: int32 */
            rank?: number | null;
            /** Format: binary */
            salt?: string | null;
        };
        NotesGroupPatchRequest: {
            /** Format: binary */
            enc_group_metadata?: string | null;
            /** Format: binary */
            enc_group_name?: string | null;
            is_deleted?: boolean | null;
            /** Format: int32 */
            rank?: number | null;
        };
        SmalltalkNote: {
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds
             * @example 1715760000000
             */
            created_at: number;
            /** Format: binary */
            enc_content?: string | null;
            /** Format: binary */
            enc_name: string;
            /** Format: uuid */
            group_id?: string | null;
            /** Format: uuid */
            id: string;
            is_deleted: boolean;
            is_protected: boolean;
            password_hash?: string | null;
            /** Format: int32 */
            rank: number;
            /** Format: binary */
            salt?: string | null;
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds
             * @example 1715760000000
             */
            updated_at: number;
            /** Format: uuid */
            user_id: string;
        };
        SmalltalkNotesEvent: {
            data: {
                note: components["schemas"]["SmalltalkNote"];
            };
            /** @enum {string} */
            type: "NoteAdded";
        } | {
            data: {
                note: components["schemas"]["SmalltalkNote"];
                /** Format: uuid */
                note_id: string;
            };
            /** @enum {string} */
            type: "NoteUpdated";
        } | {
            data: {
                /** Format: uuid */
                note_id: string;
            };
            /** @enum {string} */
            type: "NoteDeleted";
        } | {
            data: {
                /** Format: uuid */
                note_id: string;
            };
            /** @enum {string} */
            type: "NoteForgotten";
        } | {
            data: {
                group: components["schemas"]["SmalltalkNotesGroup"];
            };
            /** @enum {string} */
            type: "GroupCreated";
        } | {
            data: {
                group: components["schemas"]["SmalltalkNotesGroup"];
                /** Format: uuid */
                group_id: string;
            };
            /** @enum {string} */
            type: "GroupUpdated";
        } | {
            data: {
                /** Format: uuid */
                group_id: string;
            };
            /** @enum {string} */
            type: "GroupDeleted";
        };
        SmalltalkNotesGroup: {
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds
             * @example 1715760000000
             */
            created_at: number;
            /** Format: binary */
            enc_group_metadata?: string | null;
            /** Format: binary */
            enc_group_name: string;
            /** Format: uuid */
            id: string;
            is_deleted: boolean;
            /** Format: int32 */
            rank: number;
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds
             * @example 1715760000000
             */
            updated_at: number;
            /** Format: uuid */
            user_id: string;
        };
        SmalltalkNotesMessage: {
            /** Format: uuid */
            id: string;
            namespace: components["schemas"]["Namespaces"];
            payload: components["schemas"]["SmalltalkNotesEvent"];
        };
        SmalltalkNotesSyncResponse: {
            groups: components["schemas"]["SmalltalkNotesGroup"][];
            notes: components["schemas"]["SmalltalkNote"][];
        };
        /** @enum {string} */
        UserRole: "devin" | "owen" | "mrd" | "trusted" | "user";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description returns 200 if service alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    delete_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description pretty easy to understand what this means. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description removes user from the lazily created db */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invalidate_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description pretty easy to understand what this means. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removes uuid from HashSet defined in state, forces checks on next request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Interal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_group: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteGroupCreateRequest"];
            };
        };
        responses: {
            /** @description created note */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the id of the specific group to soft delete */
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deletes group and broadcasts the state on websocket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the id of the specific group to update */
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesGroupPatchRequest"];
            };
        };
        responses: {
            /** @description updates group and broadcasts update on websocket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_note: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreateRequest"];
            };
        };
        responses: {
            /** @description created note */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    soft_del_note: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the id of the specific note to soft delete */
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description updates note state and broadcasts update on websocket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_note: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description the id of the specific note to update */
                note_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotePatchRequest"];
            };
        };
        responses: {
            /** @description updates note and broadcasts update on websocket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    note_sync: {
        parameters: {
            query: {
                /** @description unix timestamp in milliseconds to grab notes after */
                since: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description lists notes and groups with an updated at time higher than the since param */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmalltalkNotesSyncResponse"][];
                };
            };
            /** @description Credentials Incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
