[package]
name = "dln-cli"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dln-core.workspace = true
tokio.workspace = true
anyhow.workspace = true

clap = {workspace = true, features = ["derive", "env"]}
clap_derive.workspace = true
clap_complete.workspace = true
indicatif.workspace = true
inquire.workspace = true
owo-colors.workspace = true
comfy-table.workspace = true
